[package]
name = "worker"
version = "0.1.0"
edition = "2021"

[dependencies]
ping-rs = "0.1.2"
sqlx = { version = "0.8.2", features = ["macros", "postgres", "runtime-tokio"] }
tokio = { version = "1.40.0", features = ["full"] }
